//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "equipos")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub cliente_id: Option<i32>,
    pub marca: Option<String>,
    pub modelo: Option<String>,
    pub serie: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub descripcion: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::clientes::Entity",
        from = "Column::ClienteId",
        to = "super::clientes::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Clientes,
    #[sea_orm(has_many = "super::diagnosticos::Entity")]
    Diagnosticos,
    #[sea_orm(has_many = "super::fichasentrega::Entity")]
    Fichasentrega,
}

impl Related<super::clientes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clientes.def()
    }
}

impl Related<super::diagnosticos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Diagnosticos.def()
    }
}

impl Related<super::fichasentrega::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Fichasentrega.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
