//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use super::clientes::Entity as Clientes;
pub use super::diagnosticos::Entity as Diagnosticos;
pub use super::equipos::Entity as Equipos;
pub use super::fichasentrega::Entity as Fichasentrega;
pub use super::tecnicos::Entity as Tecnicos;
